In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('insurance.csv')
print(f"Shape: {df.shape}")

Shape: (1338, 7)

In [5]:
print(f"Datatypes: \n{df.dtypes}")

Datatypes:
age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [7]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(1)

In [13]:
df=df.drop_duplicates()

In [14]:
df.shape

(1337, 7)

In [15]:
df.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [16]:
df.to_csv('cleaned_insurance.csv', index=False)

In [17]:
new_df=pd.read_csv('cleaned_insurance.csv')

In [18]:
new_df.shape

(1337, 7)