In [3]:
import pandas as pd

df=pd.read_csv('cleaned_insurance.csv')

In [4]:
df['smoke_enc']=df['smoker'].map({'no':0, 'yes':1})

In [5]:
df

      age     sex     bmi  children smoker     region      charges  smoke_enc
0      19  female  27.900         0    yes  southwest  16884.92400          1
1      18    male  33.770         1     no  southeast   1725.55230          0
2      28    male  33.000         3     no  southeast   4449.46200          0
3      33    male  22.705         0     no  northwest  21984.47061          0
4      32    male  28.880         0     no  northwest   3866.85520          0
...   ...     ...     ...       ...    ...        ...          ...        ...
1332   50    male  30.970         3     no  northwest  10600.54830          0
1333   18  female  31.920         0     no  northeast   2205.98080          0
1334   18  female  36.850         0     no  southeast   1629.83350          0
1335   21  female  25.800         0     no  southwest   2007.94500          0
1336   61  female  29.070         0    yes  northwest  29141.36030          1

[1337 rows x 8 columns]

In [6]:
df['sex_enc']=df['sex'].map({'female':0, 'male':1})

In [7]:
df

,age,sex,bmi,children,smoker,region,charges,smoke_enc,sex_enc
0,19,female,27.900,0,yes,southwest,16884.92400,1,0
1,18,male,33.770,1,no,southeast,1725.55230,0,1
2,28,male,33.000,3,no,southeast,4449.46200,0,1
3,33,male,22.705,0,no,northwest,21984.47061,0,1
4,32,male,28.880,0,no,northwest,3866.85520,0,1
...,...,...,...,...,...,...,...,...,...
1332,50,male,30.970,3,no,northwest,10600.54830,0,1
1333,18,female,31.920,0,no,northeast,2205.98080,0,0
1334,18,female,36.850,0,no,southeast,1629.83350,0,0
1335,21,female,25.800,0,no,southwest,2007.94500,0,0
1336,61,female,29.070,0,yes,northwest,29141.36030,1,0

In [8]:
df['is_obese']=(df['bmi']>=30).astype(int)

In [9]:
df['is_obese']

0       0
1       1
2       1
3       0
4       0
       ..
1332    1
1333    1
1334    1
1335    0
1336    0
Name: is_obese, Length: 1337, dtype: int64

In [12]:
df['smoker_obese']=df['smoke_enc']*df['is_obese']

In [13]:
df['smoker_obese']

0       0
1       0
2       0
3       0
4       0
       ..
1332    0
1333    0
1334    0
1335    0
1336    0
Name: smoker_obese, Length: 1337, dtype: int64

In [15]:
df['smoker_obese'].unique()

array([0, 1])